package project.iksandecade.playaudioonlist.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import project.iksandecade.playaudioonlist.dao.ListAudio;

import project.iksandecade.playaudioonlist.dao.ListAudioDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig listAudioDaoConfig;

    private final ListAudioDao listAudioDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        listAudioDaoConfig = daoConfigMap.get(ListAudioDao.class).clone();
        listAudioDaoConfig.initIdentityScope(type);

        listAudioDao = new ListAudioDao(listAudioDaoConfig, this);

        registerDao(ListAudio.class, listAudioDao);
    }
    
    public void clear() {
        listAudioDaoConfig.getIdentityScope().clear();
    }

    public ListAudioDao getListAudioDao() {
        return listAudioDao;
    }

}
