package project.iksandecade.playaudioonlist.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ListAudio.
 */
public class ListAudio {

    private Long id;
    private String name;
    private Long timeStamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ListAudio() {
    }

    public ListAudio(Long id) {
        this.id = id;
    }

    public ListAudio(Long id, String name, Long timeStamp) {
        this.id = id;
        this.name = name;
        this.timeStamp = timeStamp;
    }
    public ListAudio(String name, Long timeStamp) {
        this.name = name;
        this.timeStamp = timeStamp;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
